name: Provision APIM Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - Test
      apimServiceName:
        description: 'APIM Service Name'
        required: true
        default: 'apimDev003TDC'
        type: string
      resourceGroupName:
        description: 'Resource Group Name'
        required: true
        default: 'rg-apim-dev-003'
        type: string
      location:
        description: 'Azure Region'
        required: true
        default: 'East US'
        type: choice
        options:
          - 'East US'
          - 'West US 2'
          - 'Central US'
          - 'North Europe'
          - 'West Europe'
      sku:
        description: 'APIM SKU'
        required: true
        default: 'Developer'
        type: choice
        options:
          - 'Consumption'
          - 'Developer'
          - 'Basic'
          - 'Standard'
          - 'Premium'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AZURE_RESOURCE_GROUP: ${{ github.event.inputs.resourceGroupName }}
  AZURE_LOCATION: ${{ github.event.inputs.location }}
  APIM_SERVICE_NAME: ${{ github.event.inputs.apimServiceName }}

jobs:
  validate:
    name: Validate Bicep Template
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep template
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ./infrastructure/apim.bicep
          parameters: >
            apimServiceName=${{ env.APIM_SERVICE_NAME }}
            resourceGroupName=${{ env.AZURE_RESOURCE_GROUP }}
            location="${{ env.AZURE_LOCATION }}"
            sku=${{ github.event.inputs.sku }}
            publisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
            publisherName="${{ secrets.APIM_PUBLISHER_NAME }}"
          deploymentMode: Validate

  deploy-infrastructure:
    name: Deploy APIM Infrastructure
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ github.event.inputs.environment }}
    
    outputs:
      apimServiceName: ${{ steps.deploy.outputs.apimServiceName }}
      apimGatewayUrl: ${{ steps.deploy.outputs.apimGatewayUrl }}
      apimPortalUrl: ${{ steps.deploy.outputs.apimPortalUrl }}
      apimManagementApiUrl: ${{ steps.deploy.outputs.apimManagementApiUrl }}
      apimPrincipalId: ${{ steps.deploy.outputs.apimPrincipalId }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        run: |
          az group create \
            --name ${{ env.AZURE_RESOURCE_GROUP }} \
            --location "${{ env.AZURE_LOCATION }}" \
            --tags \
              Environment=${{ github.event.inputs.environment }} \
              Project=APIM-DevPortal \
              ManagedBy=GitHub-Actions \
              CreatedBy=${{ github.actor }}

      - name: Deploy APIM Infrastructure
        id: deploy
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/apim.bicep
          parameters: >
            apimServiceName=${{ env.APIM_SERVICE_NAME }}
            resourceGroupName=${{ env.AZURE_RESOURCE_GROUP }}
            location="${{ env.AZURE_LOCATION }}"
            sku=${{ github.event.inputs.sku }}
            publisherEmail=${{ secrets.APIM_PUBLISHER_EMAIL }}
            publisherName="${{ secrets.APIM_PUBLISHER_NAME }}"
          deploymentName: 'apim-deployment-${{ github.run_number }}'
          failOnStdErr: false

      - name: Display Deployment Results
        run: |
          echo "## 🚀 APIM Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Deployment Details:" >> $GITHUB_STEP_SUMMARY
          echo "- **APIM Service Name:** ${{ steps.deploy.outputs.apimServiceName }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Gateway URL:** ${{ steps.deploy.outputs.apimGatewayUrl }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Developer Portal URL:** ${{ steps.deploy.outputs.apimPortalUrl }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Management API URL:** ${{ steps.deploy.outputs.apimManagementApiUrl }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Resource Group:** ${{ env.AZURE_RESOURCE_GROUP }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Location:** ${{ env.AZURE_LOCATION }}" >> $GITHUB_STEP_SUMMARY
          echo "- **SKU:** ${{ github.event.inputs.sku }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Quick Links:" >> $GITHUB_STEP_SUMMARY
          echo "- [Azure Portal](https://portal.azure.com/#@${{ secrets.AZURE_TENANT_ID }}/resource/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.ApiManagement/service/${{ env.APIM_SERVICE_NAME }})" >> $GITHUB_STEP_SUMMARY
          echo "- [Developer Portal](${{ steps.deploy.outputs.apimPortalUrl }})" >> $GITHUB_STEP_SUMMARY

  post-deployment-config:
    name: Post-Deployment Configuration
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Wait for APIM to be ready
        run: |
          echo "Waiting for APIM service to be fully provisioned..."
          for i in {1..30}; do
            status=$(az apim show \
              --name ${{ env.APIM_SERVICE_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --query "provisioningState" \
              --output tsv)
            
            echo "Attempt $i: APIM provisioning state is $status"
            
            if [ "$status" = "Succeeded" ]; then
              echo "✅ APIM service is ready!"
              break
            fi
            
            if [ $i -eq 30 ]; then
              echo "❌ Timeout waiting for APIM to be ready"
              exit 1
            fi
            
            sleep 60
          done

      - name: Configure APIM Settings
        run: |
          echo "Configuring APIM settings..."
          
          # Enable developer portal
          az apim update \
            --name ${{ env.APIM_SERVICE_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --set properties.developerPortalStatus=Enabled
          
          echo "✅ APIM configuration completed!"

      - name: Create PR Comment with Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🚀 APIM Infrastructure Deployed Successfully!
            
            ### 📋 Deployment Details:
            - **APIM Service Name:** ${{ needs.deploy-infrastructure.outputs.apimServiceName }}
            - **Gateway URL:** ${{ needs.deploy-infrastructure.outputs.apimGatewayUrl }}
            - **Developer Portal URL:** ${{ needs.deploy-infrastructure.outputs.apimPortalUrl }}
            - **Management API URL:** ${{ needs.deploy-infrastructure.outputs.apimManagementApiUrl }}
            - **Resource Group:** ${{ env.AZURE_RESOURCE_GROUP }}
            - **Location:** ${{ env.AZURE_LOCATION }}
            - **SKU:** ${{ github.event.inputs.sku }}
            
            ### 🔗 Quick Links:
            - [Azure Portal](https://portal.azure.com/#@${{ secrets.AZURE_TENANT_ID }}/resource/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.ApiManagement/service/${{ env.APIM_SERVICE_NAME }})
            - [Developer Portal](${{ needs.deploy-infrastructure.outputs.apimPortalUrl }})
            
            ### ✅ Next Steps:
            1. Access the developer portal to customize the design
            2. Configure APIs and products
            3. Set up policies and transformations
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });