name: Run - Release

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      SOURCE_FOLDER_PATH:
        description: 'Folder where the captured artifacts are stored'
        required: true
        type: string
        default: 'APIM'

jobs:
  release-dev:
    uses: ./.github/workflows/release-with-env.yaml
    with:
      ENVIRONMENT: development
      SOURCE_FOLDER_PATH: ${{ github.event.inputs.SOURCE_FOLDER_PATH || 'APIM' }}
    secrets: inherit
  release-stage:
    needs: release-dev
    uses: ./.github/workflows/release-with-env.yaml
    with:
      ENVIRONMENT: Test
      SOURCE_FOLDER_PATH: ${{ github.event.inputs.SOURCE_FOLDER_PATH || 'APIM' }}
    secrets: inherit
